import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined
const supabasePublishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined

export type AuthCallbackIntent = 'invite' | 'recovery' | null

interface AuthCallbackState {
  intent: AuthCallbackIntent
  error: string
}

function readAuthCallbackState(): AuthCallbackState {
  if (typeof window === 'undefined') return { intent: null, error: '' }

  const url = new URL(window.location.href)
  const query = url.searchParams
  const fragment = new URLSearchParams(url.hash.replace(/^#/, ''))
  const authAction = query.get('auth_action')
  const callbackType = query.get('type') || fragment.get('type')
  const errorDescription = query.get('error_description') || fragment.get('error_description') || ''

  const intent = authAction === 'invite' || callbackType === 'invite'
    ? 'invite'
    : authAction === 'recovery' || callbackType === 'recovery'
      ? 'recovery'
      : null

  return {
    intent,
    error: errorDescription,
  }
}

export const initialAuthCallback = readAuthCallbackState()

export function clearAuthCallbackFromUrl() {
  if (typeof window === 'undefined') return
  const url = new URL(window.location.href)
  for (const key of ['auth_action', 'code', 'sb_flow_id', 'error', 'error_code', 'error_description']) {
    url.searchParams.delete(key)
  }
  if (!url.hash.startsWith('#/')) url.hash = '#/'
  window.history.replaceState(window.history.state, '', url.toString())
}

export const isSupabaseConfigured = Boolean(supabaseUrl && supabasePublishableKey)

export const supabase = isSupabaseConfigured
  ? createClient(supabaseUrl!, supabasePublishableKey!, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        // GitHub Pages is a browser-only SPA. Invite links generated by the
        // Supabase Admin API use implicit callback tokens, which must be
        // accepted before HashRouter reads the URL fragment.
        flowType: 'implicit',
      },
    })
  : null
